import json, sys

path = r"C:\Users\wagde\Kdesk-Catalog\scripts\knowledge-urls.json"
url_map = json.load(open(path, encoding="utf-8"))

ADD = {
    "npm": ["npm Documentation", "https://docs.npmjs.com/"],
    "yarn": ["Yarn Documentation", "https://yarnpkg.com/getting-started"],
    "feast": ["Feast Documentation", "https://docs.feast.dev/"],
    "feature-store": ["Feast Documentation", "https://docs.feast.dev/"],
    "slsa-verifier": ["SLSA Verifier", "https://slsa.dev/spec/v1.0/verifying-artifacts"],
    "robot": ["Robot Framework User Guide", "https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html"],
    "torch": ["PyTorch Documentation", "https://pytorch.org/docs/stable/"],
    "fastai": ["fastai Documentation", "https://docs.fast.ai/"],
    "optimum": ["Hugging Face Optimum", "https://huggingface.co/docs/optimum/index"],
    "deepspeed": ["DeepSpeed Documentation", "https://www.deepspeed.ai/"],
    "shap": ["SHAP Documentation", "https://shap.readthedocs.io/en/latest/"],
    "lime": ["LIME Explainer", "https://github.com/marcotcr/lime"],
    "fairlearn": ["Fairlearn Documentation", "https://fairlearn.org/"],
    "aif360": ["AI Fairness 360", "https://aif360.res.ibm.com/"],
    "aequitas": ["Aequitas Fairness Auditing", "https://github.com/dssg/aequitas"],
    "dice-ml": ["DiCE Counterfactual Explanations", "https://github.com/interpretml/DiCE"],
    "evidently": ["Evidently AI Documentation", "https://www.evidentlyai.com/"],
    "opendp": ["OpenDP Documentation", "https://docs.opendp.org/"],
    "laplace": ["Differential Privacy", "https://www.tensorflow.org/privacy"],
    "vertexai": ["Vertex AI Documentation", "https://cloud.google.com/vertex-ai/docs"],
    "aiplatform": ["Vertex AI Python SDK", "https://cloud.google.com/vertex-ai/docs/python-sdk/use-vertex-ai-python-sdk"],
    "alertmanager": ["Alertmanager Documentation", "https://prometheus.io/docs/alerting/latest/alertmanager/"],
    "praw": ["PRAW Documentation", "https://praw.readthedocs.io/"],
    "tweepy": ["Tweepy Documentation", "https://docs.tweepy.org/"],
    "reddit": ["Reddit API Documentation", "https://www.reddit.com/dev/api/"],
    "discord": ["Discord Developer Documentation", "https://discord.com/developers/docs"],
    "reportlab": ["ReportLab Documentation", "https://www.reportlab.com/docs/"],
    "jsdoc": ["JSDoc Documentation", "https://jsdoc.app/"],
    "matplotlib": ["Matplotlib Documentation", "https://matplotlib.org/stable/"],
    "sklearn": ["scikit-learn Documentation", "https://scikit-learn.org/stable/"],
    "ldclient": ["LaunchDarkly SDK Documentation", "https://docs.launchdarkly.com/sdk"],
    "feature-flag": ["LaunchDarkly Documentation", "https://docs.launchdarkly.com/"],
    "onnx": ["ONNX Runtime Documentation", "https://onnxruntime.ai/docs/"],
    "llamaindex": ["LlamaIndex Documentation", "https://docs.llamaindex.ai/"],
    "curl": ["curl Documentation", "https://curl.se/docs/"],
    "jq": ["jq Manual", "https://jqlang.github.io/jq/"],
    "deploy": ["Kubernetes Deployment Documentation", "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/"],
    "cost": ["FinOps Foundation", "https://www.finops.org/"],
    "cached": ["Caching Strategies", "https://aws.amazon.com/caching/"],
    "acceleration": ["ONNX Runtime Documentation", "https://onnxruntime.ai/docs/"],
    "accessibility": ["W3C Web Accessibility Initiative", "https://www.w3.org/WAI/"],
    "business": ["Google Cloud AI Adoption Framework", "https://cloud.google.com/transform/ai-adoption-framework"],
    "collaboration": ["Hugging Face Hub Documentation", "https://huggingface.co/docs/hub/"],
    "community": ["MLCommons", "https://www.mlcommons.org/"],
    "education": ["DeepLearning.AI", "https://www.deeplearning.ai/"],
    "communication": ["arXiv", "https://arxiv.org/"],
    "ethics": ["OECD AI Principles", "https://oecd.ai/en/ai-principles"],
    "legal": ["GDPR Information Portal", "https://gdpr-info.eu/"],
    "data-labeling": ["Labelbox Documentation", "https://docs.labelbox.com/docs/"],
    "data-preparation": ["Amazon SageMaker Data Preparation", "https://docs.aws.amazon.com/sagemaker/latest/dg/data-prep.html"],
    "feature-eng": ["scikit-learn Preprocessing", "https://scikit-learn.org/stable/modules/preprocessing.html"],
    "interpretability": ["SHAP Documentation", "https://shap.readthedocs.io/en/latest/"],
    "explainability": ["SHAP Documentation", "https://shap.readthedocs.io/en/latest/"],
    "fairness": ["Fairlearn Documentation", "https://fairlearn.org/"],
    "governance": ["MLflow Model Registry", "https://mlflow.org/docs/latest/model-registry.html"],
    "privacy": ["OpenMined", "https://www.openmined.org/"],
    "safety": ["Google Responsible AI", "https://ai.google/responsibility/"],
    "robustness": ["Adversarial Robustness Toolbox", "https://github.com/Trusted-AI/adversarial-robustness-toolbox"],
    "scalability": ["Kubernetes Architecture", "https://kubernetes.io/docs/concepts/architecture/"],
    "evaluation": ["MLflow LLM Evaluation", "https://mlflow.org/docs/latest/llms/llm-evaluate/"],
    "observability": ["OpenTelemetry Documentation", "https://opentelemetry.io/docs/"],
    "monitoring": ["Prometheus Documentation", "https://prometheus.io/docs/introduction/overview/"],
    "optimization": ["Optuna Documentation", "https://optuna.org/"],
    "inference": ["TensorFlow Serving", "https://www.tensorflow.org/serving"],
    "batch": ["Google Cloud Batch", "https://cloud.google.com/batch/docs"],
    "edge": ["KubeEdge", "https://github.com/kubeedge/kubeedge"],
    "embedded": ["TensorFlow Lite", "https://www.tensorflow.org/lite"],
    "hybrid": ["Google Cloud Anthos", "https://cloud.google.com/anthos/docs"],
    "streaming": ["Apache Kafka Documentation", "https://kafka.apache.org/documentation/"],
    "onprem": ["kubeadm Setup", "https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/"],
    "prompt-engineering": ["Anthropic Prompt Engineering", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering"],
    "prompt": ["Anthropic Prompt Engineering", "https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering"],
    "mlops": ["MLflow Documentation", "https://mlflow.org/docs/"],
    "reproducibility": ["DVC Documentation", "https://dvc.org/doc"],
    "runbook": ["Atlassian Incident Runbooks", "https://www.atlassian.com/incident-management/runbooks"],
    "sli": ["Google SRE Service Level Objectives", "https://sre.google/sre-book/service-level-objectives/"],
    "slo": ["Google SRE Service Level Objectives", "https://sre.google/sre-book/service-level-objectives/"],
    "capacity": ["Google SRE Managing Load", "https://sre.google/sre-book/managing-load/"],
    "postmortem": ["Google SRE Postmortem Culture", "https://sre.google/sre-book/postmortem-culture/"],
    "incident-response": ["Google SRE Effective Incident Response", "https://sre.google/sre-book/effective-incident-response/"],
    "monitor-setup": ["Prometheus Documentation", "https://prometheus.io/docs/introduction/overview/"],
    "monitor": ["Prometheus Documentation", "https://prometheus.io/docs/introduction/overview/"],
    "logging": ["Grafana Loki Documentation", "https://grafana.com/docs/loki/latest/"],
    "project": ["GitHub Projects Documentation", "https://docs.github.com/en/issues/planning-and-tracking-with-projects"],
    "auth": ["OAuth 2.0", "https://oauth.net/2/"],
    "documentation": ["MkDocs Documentation", "https://www.mkdocs.org/"],
    "doc": ["MkDocs Documentation", "https://www.mkdocs.org/"],
    "tester": ["Postman Learning Center", "https://learning.postman.com/"],
    "scanner": ["Trivy Documentation", "https://aquasecurity.github.io/trivy/"],
    "reliability": ["Google SRE Book", "https://sre.google/sre-book/table-of-contents/"],
    "performance": ["AWS Performance Efficiency Pillar", "https://docs.aws.amazon.com/wellarchitected/latest/performance-efficiency-pillar/welcome.html"],
    "agent": ["LangGraph Documentation", "https://langchain-ai.github.io/langgraph/"],
    "embedding": ["OpenAI Embeddings Guide", "https://platform.openai.com/docs/guides/embeddings"],
}

conflicts = [k for k in ADD if k in url_map]
if conflicts:
    print("ALREADY PRESENT:", conflicts)
    sys.exit(1)
url_map.update(ADD)
with open(path, "w", encoding="utf-8") as f:
    json.dump(url_map, f, indent=2, ensure_ascii=False)
    f.write("\n")
print("added", len(ADD), "keys; total", len(url_map))