"""Output writers: save_agent, pruning, and per-platform metadata."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Set

import yaml

from kdesk.converters import constants as cfg
from kdesk.converters.constants import (
    DEPRECATED_SINGLE_FILE_PLATFORMS,
    PLATFORM_INFO,
    SINGLE_FILE_PLATFORMS,
)


def write_platform_meta(platform: str, output_dir: Path, counts: Dict[str, int]):
    """Write README.md (and manifest for single-file platforms)."""
    info = PLATFORM_INFO.get(platform)
    if not info:
        return
    name, fmt, install = info
    pd = output_dir / platform
    pd.mkdir(parents=True, exist_ok=True)
    total = counts.get('agents', 0) + counts.get('skills', 0)
    readme = (
        f"# {name} ({platform})\n\n"
        f"Format: {fmt}\n\n"
        f"## Install\n{install}\n\n"
        f"## Contents\n"
        f"- {counts.get('agents', 0)} agents\n"
        f"- {counts.get('skills', 0)} skills\n"
        f"- {total} files total\n\n"
        f"Generated by Kdesk-Catalog from `universal-agents/` (2,909 YAML definitions).\n"
    )
    (pd / "README.md").write_text(readme, encoding="utf-8")
    if platform in SINGLE_FILE_PLATFORMS or platform in DEPRECATED_SINGLE_FILE_PLATFORMS:
        files = sorted(pd.glob("instructions/*.md"))
        native = SINGLE_FILE_PLATFORMS.get(platform)
        if native:
            how_to = f"Pick the instruction file for the agent or skill you need and merge its contents into your {native} (or its rule registry)."
        else:
            how_to = "Deprecated: no documented agent-instructions file. Fragments are reference material; no native file is assembled."
        manifest = {
            "platform": platform,
            "native_file": native,
            "instruction_files": [f"instructions/{f.name}" for f in files],
            "how_to_use": how_to,
        }
        (pd / "manifest.yaml").write_text(
            yaml.safe_dump(manifest, default_flow_style=False, sort_keys=False,
                           allow_unicode=True, width=100),
            encoding="utf-8",
        )
    # Generate GitHub Copilot repo-wide index
    if platform == "github_copilot":
        write_copilot_index(pd, output_dir / platform)


def write_copilot_index(platform_dir: Path, output_dir: Path):
    """Generate curated .github/copilot-instructions.md repo-wide index."""
    instructions_dir = platform_dir / ".github" / "instructions"
    if not instructions_dir.exists():
        return

    items = []
    for f in sorted(instructions_dir.glob("*.instructions.md")):
        content = f.read_text(encoding="utf-8")
        name = f.stem
        desc = ""
        for line in content.split("\n"):
            if line.startswith("description:") or (line and not line.startswith("#") and not line.startswith("---")):
                desc = line.strip()
                if desc.startswith("description:"):
                    desc = desc.split(":", 1)[1].strip()
                break
        items.append((name, desc))

    parts = [
        "# GitHub Copilot Instructions — Kdesk-Catalog",
        "",
        "> Auto-generated index of all available agents and skills.",
        "> Copy the `.github/instructions/` directory into your repo to enable.",
        "",
        f"## Contents ({len(items)} items)",
        "",
    ]

    for name, desc in items:
        parts.append(f"- **{name}**: {desc[:120]}")

    parts.append("")
    parts.append("---")
    parts.append("")
    parts.append("Generated by Kdesk-Catalog. See `platform-agents/github_copilot/.github/instructions/` for per-item files.")

    index_path = platform_dir / ".github" / "copilot-instructions.md"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text("\n".join(parts), encoding="utf-8")
    print(f"  [OK] github_copilot/.github/copilot-instructions.md ({len(items)} items)")


def save_agent(agent_data: Dict[str, Any], platform: str, output_dir: Path):
    """Save agent in platform-specific format; returns the written file path (or None)."""
    platform_dir = output_dir / platform
    platform_dir.mkdir(parents=True, exist_ok=True)

    if 'rel_path' in agent_data:
        file_path = platform_dir / agent_data['rel_path']
        file_path.parent.mkdir(parents=True, exist_ok=True)
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(agent_data['content'])
        if not cfg.QUIET:
            print(f"  [OK] {platform}/{agent_data['rel_path']}")
        return file_path

    name = agent_data['name']

    if platform == "claude_code":
        file_path = platform_dir / f"{name}.json"
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(agent_data, f, indent=2)
    elif platform == "github_copilot":
        file_path = platform_dir / agent_data['prompt_file']
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(agent_data['prompt'])
    elif platform == "generic":
        file_path = platform_dir / f"{name}.json"
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(agent_data, f, indent=2)
    else:
        file_path = None

    if not cfg.QUIET:
        print(f"  [OK] {platform}/{name}")
    return file_path


def prune_platform_dir(platform: str, output_dir: Path, written: Set[str]) -> int:
    """Remove stale files in the platform dir that were not written this run.
    Meta files (README.md, manifest.yaml) are preserved. Returns count pruned."""
    platform_dir = output_dir / platform
    if not platform_dir.is_dir():
        return 0
    pruned = 0
    for f in sorted(platform_dir.rglob("*")):
        if f.is_file() and f.name not in ("README.md", "manifest.yaml"):
            if f.resolve().as_posix() not in written:
                try:
                    f.unlink()
                    pruned += 1
                except OSError:
                    pass
    for d in sorted(platform_dir.rglob("*"), reverse=True):
        if d.is_dir() and not any(d.iterdir()):
            try:
                d.rmdir()
                pruned += 1
            except OSError:
                pass
    return pruned
